name: loogisti
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.9.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  mobile_device_identifier: ^0.0.2
  dio: ^5.4.0
  internet_connection_checker: ^1.0.0+1
  flutter_local_notifications: ^16.2.0
  flutter_secure_storage: ^9.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  lit_relative_date_time: ^1.2.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  loading_animation_widget: ^1.2.0+4
  animated_text_kit: ^4.2.2
  country_pickers: ^2.0.0
  string_validator: ^1.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  flutter_switch: ^0.3.2
  image_picker_plus:
    git:
      url: https://github.com/farhioussama1969/image_picker_flutter.git
      ref: main
  pretty_qr_code: ^3.0.0
  animated_switcher_plus: ^1.1.0
  smooth_page_indicator: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  percent_indicator: ^4.2.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  like_button: ^2.0.5
  flutter_datetime_picker_plus: ^2.1.0



  flutter:
    sdk: flutter

dependency_overrides:
  photo_manager: ^3.0.0-dev.2

dev_dependencies:
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/logos/
    - assets/fonts/
    - assets/audios/

  fonts:
    - family: bahij_regular
      fonts:
        - asset: assets/fonts/bahij_regular.ttf
    - family: bahij_bold
      fonts:
        - asset: assets/fonts/bahij_bold.ttf



flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/app_icon.jpg"

